setenv LESS CMs
setenv PATH "/opt/SDK/jdk/bin:${PATH}:${HOME}/bin:/opt/SDK/bin:"
setenv JAVA_HOME /opt/SDK/jdk
setenv DERBY_INSTALL /opt/SDK/jdk/db
setenv CLASSPATH "${DERBY_INSTALL}/lib/derby.jar:${DERBY_INSTALL}/lib/derbytools.jar:${DERBY_INSTALL}/lib/derbynet.jar:${DERBY_INSTALL}/lib/derbyclient.jar:.:"
setenv IJ_HOST localhost
setenv IJ_PORT 1527
setenv IJ_USER APP
setenv IJ_PASSWORD APP
